ENCODER_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no
CAPS_WORD_ENABLE = yes
SWAP_HANDS_ENABLE = yes
TAP_DANCE_ENABLE = no
MAGIC_ENABLE = yes

# Optimizations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
GRAVE_ESC_ENABLE = no 
MUSIC_ENABLE = no